### ISSUE TITLE
Facing issue in Windows to run this app on any target.

### ISSUE THREAD

**Issue by Hey-Deepak** [SEAbdulbasit/recipe-app#10]
I want to clone this app want to learn and contribute.
Right now, I am struggling to run this app.

**Comment by SEAbdulbasit** [comment]
Hi,
What kind of issue you are facing?

**Comment by SEAbdulbasit** [comment]
Hi,
What kind of issue you are facing?

**Comment by Hey-Deepak** [comment]
Stupid Gradle issue... Let me try more and then I will try to paste here.
Seems like I don't have mac and it is related to source target.
