### ISSUE TITLE
Recipe List Item Picture

### ISSUE THREAD

**Issue by syedalizaib** [SEAbdulbasit/recipe-app#8]
The recipe picture of the first item opened stays stickied on top. 
![Simulator Screenshot - iPhone 15 - 2024-04-08 at 00 15 46](https://github.com/SEAbdulbasit/recipe-app/assets/25015289/a2d19204-9a97-4574-a177-fb639becf0f7)

**Comment by SEAbdulbasit** [comment]
Hi, I have pushed a fix, and the issue is being fixed.
